GET http://localhost:3001/employee/1
###
POST http://localhost:3001/employee/login
Content-Type: application/json

{
        "email": "ezmail2@ezmail.com",
        "password": "ezpass2"
}

###
POST http://localhost:3001/employee/
Content-Type: application/json

{
        "email": "admin@zmail.com",
        "password": "admin",
        "first_name": "Admin",
        "last_name": "Admin",
        "role": "manager",
        "phone_number": "011-090-0900"
}

###
GET http://localhost:3001/employee/1
Content-Type: application/json

{
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY3NzEwMDA2NH0.6J6jUQ-Ms2xnXE_btvIDXZrX_Bcgw1OfETSyjsXT7go" 
}

###
GET http://localhost:3001/employee/all
Content-Type: application/json

{
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY3NzEwMTk0Mn0.Se1jTMCx8hkjpEAMpe7abLkbr4RE_Jd-fPe7hEsdzAo"
}